services:
  algae:
    image: ghcr.io/tnraro/algae:main
    ports:
      - ${PORT:-41943}:41943
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data

volumes:
  data:
